# SSL configuration
ssl = required
ssl_cert = </etc/letsencrypt/live/{{HOSTNAME}}/fullchain.pem
ssl_key = </etc/letsencrypt/live/{{HOSTNAME}}/privkey.pem
ssl_min_protocol = TLSv1.2
ssl_prefer_server_ciphers = yes
